import os
import shutil
cwd = os.getcwd()
os.system("rm -rf txt_csv_files")
os.system("rm -rf we_inputs")
os.system("rm -rf dat_files")
os.system("rm -rf pickle_files")
os.system("rm -rf system_files")
os.system("mkdir txt_csv_files")
os.system("mkdir we_inputs")
os.system("mkdir dat_files")
os.system("mkdir pickle_files")
os.system("mkdir system_files")
shutil.move(cwd + "/" + "c1_frame_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c1_frame_1d.txt")
shutil.move(cwd + "/" + "c12_frame_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c12_frame_1d.txt")
shutil.move(cwd + "/" + "c123_frame_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c123_frame_1d.txt")
shutil.move(cwd + "/" + "c1_frame_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c1_frame_2d.txt")
shutil.move(cwd + "/" + "c12_frame_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c12_frame_2d.txt")
shutil.move(cwd + "/" + "c123_frame_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "c123_frame_2d.txt")
shutil.move(cwd + "/" + "pA_c1_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c1_1d.txt")
shutil.move(cwd + "/" + "pA_c12_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c12_1d.txt")
shutil.move(cwd + "/" + "pA_c123_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c123_1d.txt")
shutil.move(cwd + "/" + "pA_c1_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c1_2d.txt")
shutil.move(cwd + "/" + "pA_c12_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c12_2d.txt")
shutil.move(cwd + "/" + "pA_c123_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c123_2d.txt")
shutil.move(cwd + "/" + "pA_c1_arranged_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c1_arranged_1d.txt")
shutil.move(cwd + "/" + "pA_c12_arranged_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c12_arranged_1d.txt")
shutil.move(cwd + "/" + "pA_c123_arranged_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c123_arranged_1d.txt")
shutil.move(cwd + "/" + "pA_c1_arranged_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c1_arranged_2d.txt")
shutil.move(cwd + "/" + "pA_c12_arranged_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c12_arranged_2d.txt")
shutil.move(cwd + "/" + "pA_c123_arranged_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "pA_c123_arranged_2d.txt")
shutil.move(cwd + "/" + "ref_1d.txt", cwd + "/" + "txt_csv_files" +  "/" + "ref_1d.txt")
shutil.move(cwd + "/" + "ref_2d.txt", cwd + "/" + "txt_csv_files" +  "/" + "ref_2d.txt")
shutil.move(cwd + "/" + "df_1d.csv", cwd + "/" + "txt_csv_files" +  "/" + "df_1d.csv")
shutil.move(cwd + "/" + "df_2d.csv", cwd + "/" + "txt_csv_files" +  "/" + "df_2d.csv")
shutil.move(cwd + "/" + "we_input_c1_1d.txt", cwd + "/" + "we_inputs" + "/" +  "we_input_c1_1d.txt" )
shutil.move(cwd + "/" + "we_input_c12_1d.txt", cwd + "/" + "we_inputs" +  "/" + "we_input_c12_1d.txt")
shutil.move(cwd + "/" + "we_input_c123_1d.txt", cwd + "/" + "we_inputs" +  "/" + "we_input_c123_1d.txt" )
shutil.move(cwd + "/" + "we_input_c1_2d.txt", cwd + "/" + "we_inputs" +  "/" + "we_input_c1_2d.txt" )
shutil.move(cwd + "/" + "we_input_c12_2d.txt", cwd + "/" + "we_inputs" + "/" +  "we_input_c12_2d.txt")
shutil.move(cwd + "/" + "we_input_c123_2d.txt", cwd + "/" + "we_inputs" +  "/" + "we_input_c123_2d.txt" )
shutil.move(cwd + "/" + "weights.dat", cwd + "/" + "dat_files" +  "/" + "weights.txt")
shutil.move(cwd + "/" + "rmsd.dat", cwd + "/" + "dat_files" +  "/" + "rmsd.txt")
shutil.move(cwd + "/" + "rmsd_rg.dat", cwd + "/" + "dat_files" +  "/" + "rmsd_rg.txt")
shutil.move(cwd + "/" + "prob_c1_1d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c1_1d_list.pickle")
shutil.move(cwd + "/" + "prob_c12_1d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c12_1d_list.pickle")
shutil.move(cwd + "/" + "prob_c123_1d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c123_1d_list.pickle")
shutil.move(cwd + "/" + "prob_c1_2d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c1_2d_list.pickle")
shutil.move(cwd + "/" + "prob_c12_2d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c12_2d_list.pickle")
shutil.move(cwd + "/" + "prob_c123_2d_list.pickle", cwd + "/" + "pickle_files" +  "/" + "prob_c123_2d_list.pickle")
shutil.move(cwd + "/" + "pdb_1d_c1.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_1d_c1.pickle")
shutil.move(cwd + "/" + "pdb_1d_c12.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_1d_c12.pickle")
shutil.move(cwd + "/" + "pdb_1d_c123.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_1d_c123.pickle")
shutil.move(cwd + "/" + "pdb_2d_c1.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_2d_c1.pickle")
shutil.move(cwd + "/" + "pdb_2d_c12.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_2d_c12.pickle")
shutil.move(cwd + "/" + "pdb_2d_c123.pickle", cwd + "/" + "pickle_files" +  "/" + "pdb_2d_c123.pickle")
shutil.move(cwd + "/" + "frames_c1_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c1_1d.pickle")
shutil.move(cwd + "/" + "frames_c12_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c12_1d.pickle")
shutil.move(cwd + "/" + "frames_c123_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c123_1d.pickle")
shutil.move(cwd + "/" + "frames_c1_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c1_2d.pickle")
shutil.move(cwd + "/" + "frames_c12_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c12_2d.pickle")
shutil.move(cwd + "/" + "frames_c123_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "frames_c123_2d.pickle")
shutil.move(cwd + "/" + "indices_c1_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c1_1d.pickle")
shutil.move(cwd + "/" + "indices_c12_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c12_1d.pickle")
shutil.move(cwd + "/" + "indices_c123_1d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c123_1d.pickle")
shutil.move(cwd + "/" + "indices_c1_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c1_2d.pickle")
shutil.move(cwd + "/" + "indices_c12_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c12_2d.pickle")
shutil.move(cwd + "/" + "indices_c123_2d.pickle", cwd + "/" + "pickle_files" +  "/" + "indices_c123_2d.pickle")
shutil.move(cwd + "/" + "system_final.inpcrd", cwd + "/" + "system_files" +  "/" + "system_final.inpcrd")
shutil.move(cwd + "/" + "system_final.nc", cwd + "/" + "system_files" +  "/" + "system_final.nc")
shutil.move(cwd + "/" + "system_final.out", cwd + "/" + "system_files" +  "/" + "system_final.out")
shutil.move(cwd + "/" + "system_final.prmtop", cwd + "/" + "system_files" +  "/" + "system_final.prmtop")
shutil.move(cwd + "/" + "system_final.rst", cwd + "/" + "system_files" +  "/" + "system_final.rst")
shutil.move(cwd + "/" + "gamd.log", cwd + "/" + "system_files" +  "/" + "gamd.log")
shutil.move(cwd + "/" + "md.in", cwd + "/" + "system_files" +  "/" + "md.in")
shutil.move(cwd + "/" + "mdinfo", cwd + "/" + "system_files" +  "/" + "mdinfo")
shutil.move(cwd + "/" + "gamd-restart.dat", cwd + "/" + "system_files" +  "/" + "gamd-restart.dat")
