import os
cwd = os.getcwd()
os.chdir(cwd + "/" + "gamd_simulations")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "dihedral_threshold_lower")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "dihedral_threshold_upper")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "dual_threshold_lower")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "dual_threshold_upper")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "total_threshold_lower")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations" + "/" + "total_threshold_upper")
os.system("pmemd.cuda -O -i md.in -o system_final.out -p system_final.prmtop -c system_final.inpcrd -r system_final.rst -x system_final.nc")
os.chdir(cwd + "/" + "gamd_simulations")
os.chdir(cwd)
