name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - curl
  - matplotlib
  - openmm
  - seaborn
  - pandas
  - mdtraj
  - jupyterlab
  - pip
  - pip:
    - sphinx-autoapi

